const state={cart:[]};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const cartDrawer=$('#cartDrawer'),scrim=$('#scrim'),cartItems=$('#cartItems'),cartCount=$('#cartCount'),cartTotal=$('#cartTotal'),toast=$('#toast');
function money(v){return `RM${v.toFixed(2)}`}
function openCart(){cartDrawer.classList.add('open');scrim.classList.add('on');cartDrawer.setAttribute('aria-hidden','false')}
function closeCart(){cartDrawer.classList.remove('open');scrim.classList.remove('on');cartDrawer.setAttribute('aria-hidden','true')}
function flash(msg='Added to bag'){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1700)}
function addItem(name,price){const hit=state.cart.find(i=>i.name===name);if(hit)hit.qty++;else state.cart.push({name,price,qty:1});renderCart();flash(`${name} added`)}
function renderCart(){cartCount.textContent=state.cart.reduce((s,i)=>s+i.qty,0);const total=state.cart.reduce((s,i)=>s+i.price*i.qty,0);cartTotal.textContent=money(total);if(!state.cart.length){cartItems.innerHTML='<p class="empty-cart">Your bag is empty.</p>';return}cartItems.innerHTML=state.cart.map((i,idx)=>`<div class="cart-item"><div class="cart-swatch"></div><div><h4>${i.name}</h4><small>${i.qty} × ${money(i.price)}</small></div><button class="remove-item" data-remove="${idx}">Remove</button></div>`).join('');$$('[data-remove]').forEach(b=>b.onclick=()=>{state.cart.splice(+b.dataset.remove,1);renderCart()})}
$$('.product-card').forEach(card=>card.querySelector('.add-btn').addEventListener('click',()=>addItem(card.dataset.product,+card.dataset.price)));
$('[data-add-bundle]').addEventListener('click',()=>addItem('Discovery Set',49));
$('#cartButton').onclick=openCart;$('#closeCart').onclick=closeCart;scrim.onclick=closeCart;
$('#waCheckout').onclick=()=>{if(!state.cart.length){flash('Your bag is empty');return}const lines=state.cart.map(i=>`• ${i.name} × ${i.qty} = ${money(i.price*i.qty)}`).join('\n');const total=state.cart.reduce((s,i)=>s+i.price*i.qty,0);const msg=`Hi ASFT, saya nak order:\n${lines}\n\nTotal: ${money(total)}\nBoleh bantu saya proceed?`;window.open(`https://wa.me/601115049049?text=${encodeURIComponent(msg)}`,'_blank')};
$('#checkoutButton').onclick=()=>{if(!state.cart.length){flash('Your bag is empty');return}flash('Payment gateway ready to be connected')};
const mobileMenu=$('#mobileMenu');$('#menuButton').onclick=()=>mobileMenu.classList.toggle('open');$$('#mobileMenu a').forEach(a=>a.onclick=()=>mobileMenu.classList.remove('open'));

const finder=$('#finderModal'),quizStage=$('#quizStage');let answers=[];const questions=[{q:'What should your perfume say first?',o:[['Clean and effortless','fresh'],['Warm and magnetic','warm'],['Dark and confident','bold'],['Soft and elegant','soft']]},{q:'When will you wear it most?',o:[['Everyday / office','fresh'],['Date night','warm'],['Events / night out','bold'],['Anytime, close to skin','soft']]},{q:'Pick one atmosphere.',o:[['White linen + morning light','fresh'],['Golden sunset + warm skin','warm'],['Black suit + city after dark','bold'],['Quiet room + fresh sheets','soft']]}];
function renderQuestion(){const i=answers.length;if(i>=questions.length){const counts=answers.reduce((a,x)=>(a[x]=(a[x]||0)+1,a),{});const type=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0];const results={fresh:['White Musk','Neroli, white tea and soft musk. Clean, modern and easy to wear.'],warm:['Amber Bloom','Saffron, jasmine and golden amber. Warm, inviting and memorable.'],bold:['Noir 01','Bergamot, black pepper and amberwood. Strong presence for evening wear.'],soft:['White Musk','Soft musk with airy tea notes for a close, effortless scent.']};const [name,desc]=results[type];quizStage.innerHTML=`<div class="quiz-result"><span class="quiz-progress">YOUR MATCH</span><h3>${name}</h3><p>${desc}</p><button class="btn btn-gold" id="resultAdd">Add ${name} to bag</button></div>`;$('#resultAdd').onclick=()=>{const card=[...$$('.product-card')].find(c=>c.dataset.product===name);addItem(name,card?+card.dataset.price:69);finder.classList.remove('open');openCart()};return}const cur=questions[i];quizStage.innerHTML=`<span class="quiz-progress">QUESTION 0${i+1} / 03</span><h3 class="quiz-title">${cur.q}</h3><div class="quiz-options">${cur.o.map(x=>`<button class="quiz-option" data-value="${x[1]}">${x[0]}</button>`).join('')}</div>`;$$('.quiz-option').forEach(b=>b.onclick=()=>{answers.push(b.dataset.value);renderQuestion()})}
function openFinder(){answers=[];renderQuestion();finder.classList.add('open');finder.setAttribute('aria-hidden','false')}
$$('[data-open-finder]').forEach(b=>b.onclick=openFinder);$('#closeFinder').onclick=()=>finder.classList.remove('open');finder.addEventListener('click',e=>{if(e.target===finder)finder.classList.remove('open')});

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.1});$$('.reveal').forEach(el=>observer.observe(el));
renderCart();
